### ISSUE TITLE
Upload base set of sequences

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#10]

**Comment by pjotrp** [comment]
@tetron can you list here how far you got so someone may take over

**Comment by tetron** [comment]
Here is the GenBank SARS-Cov-2 page:

https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=SARS-CoV-2,%20taxid:2697049

Biopython supports the Entrez API:

https://biopython.org/docs/1.76/api/Bio.Entrez.html

```
from Bio import Entrez
```

We can search for sequences and get accession numbers this way:

```
Entrez.read(Entrez.esearch(db='nuccore', term='SARS-CoV-2', idtype='acc', retmax='10000'))
```

note: I couldn't figure out how to query directly on `taxid:2697049`, it seems like it ought to be possible.

We can retrieve fasta files this way:
```
Entrez.efetch(db='nuccore', id='MN938384.1', rettype='fasta').read()
```

We can get metadata this way:

```
Entrez.efetch(db='nuccore', id='MN938384.1', retmode='xml').read()
```

To do:

1. Get a list of accession numbers (either via the API or downloading a CSV)
2. Grab each fasta file
3. Grab the metadata and translate it our metadata
4. Upload each sequence along with its metadata

**Comment by AndreaGuarracino** [comment]
Thank you for your initial work thanks to which I have all the sequences and all the metadata (890 entry), and now I am starting to parse the latter. Regarding the [minimal](https://github.com/arvados/bh20-seq-resource/blob/master/example/minimal_example.yaml) metadata example, are all this records **mandatory**? I will try to fill the [maximum](https://github.com/arvados/bh20-seq-resource/blob/master/example/metadata.yaml) metadata, but (for now) I am not even sure all the information in minimum metadata are present in the metadata files recovered with eseach (like sex for example).

**Comment by pjotrp** [comment]
Thank you @AndreaGuarracino. Have a look at http://covid-19.genenetwork.org/. That is the current list of metadata derived from https://github.com/arvados/bh20-seq-resource/blob/master/bh20sequploader/bh20seq-schema.yml. Just try to fill in what you can, we'll have to rerun your code ourselves again. Add your script to our repo in ./scripts/genbank or something and do a PR.

**Comment by AndreaGuarracino** [comment]
I've pushed-requested the first release of the script in the ./scripts directory. Maybe not too much elegant, but it seems to work. It downloads some IDs using esearch, merges them with the accession list downloaded from NCBI Virus, requests all the metadata (which include the sequences, so less server-requests to do!), and prepare and write a fasta file and a yaml file for each accession. When the metadata schema will be definitive, maybe a little work will be needed for the fields which remain empty in the metadata.

**Comment by pjotrp** [comment]
Great! I merged for further testing/development. At this stage, can you generate some metadata and run it by @LLTommy?  @AndreaGuarracino add your name and affiliation to the paper in the ./paper directory.

**Comment by AndreaGuarracino** [comment]
I've added the control of the type of the ID, removing what is not genomic DNA (that is, mRNAs, ncRNAs, proteins, and predicted models). I still left the esearch requests, but for the moment the accession list from NCBI Virus already includes everything.

**Comment by pjotrp** [comment]
I think this is complete. Closing.
