### ISSUE TITLE
Better sample id management

### ISSUE THREAD

**Issue by tetron** [arvados/bh20-seq-resource#103]
From discussion 27 August 2020:

- [x] `sample_id` should be the same between the metadata file and fasta header from upload, should be validated
- [x]  If an uploaded, valid sequence has the same sample id as an existing validated sequence, copy the new sequence/metadata to the existing collection.   Enable versioning on Arvados
- [ ]  Cleaning up
    - [x] Clean up existing sequences,
    - [ ] merge based on sequence_label and take the latest (most recent created_at).
    - [ ] revalidate previously validated samples that have invalid dates or specimen fields

Originally on the list I don't think we're doing this right now:

For namespacing identifiers, sample_id should be a URI.  Add command line option to uploader to give URI prefix. Give instructions to put your institution's web page if you don't know what else to use.  Validate that sample_id is a valid URI.

**Comment by tetron** [comment]
Also, the RDF output should use the sample_id as the subject.

**Comment by pjotrp** [comment]
Currently we have a sample name (provided by the uploader), an identifiers.org ID (for NCBI at least) and the Arvados ID for the FASTA file. This is all tied together by an anonymous node id. The [query](http://sparql.genenetwork.org/sparql/?default-graph-uri=&query=select+%3Fdate+%3Fname+%3Fidentifier+%3Fseq%0D%0A%7B%0D%0A++++%3Fseq+%3Chttp%3A%2F%2Fbiohackathon.org%2Fbh20-seq-schema%23MainSchema%2Fsample%3E+%3Fsample+.%0D%0A%0D%0A++++%3Fsample+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGAZ_00000448%3E+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1223%3E+.%0D%0A++++%3Fsample+%3Chttp%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C25164%3E+%3Fdate+.%0D%0A++++%3Fsample+%3Chttp%3A%2F%2Fsemanticscience.org%2Fresource%2FSIO_000115%3E+%3Fname+.%0D%0A++++%3Fsample+%3Chttp%3A%2F%2Fedamontology.org%2Fdata_2091%3E+%3Fidentifier+.%0D%0A%7D+order+by+%3Fdate&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) is

```sparql
PREFIX pubseq: <http://biohackathon.org/bh20-seq-schema#MainSchema/>
PREFIX sio: <http://semanticscience.org/resource/>
select distinct ?sample ?p ?o
{
   ?sample sio:SIO_000115 "MT326090.1" .
   ?sample ?p ?o .
}
```

@tetron what we need is a unique identifier that links up metadata and FASTA sequence. This identifier can display a page on the website showing this information. I'll use it to link from the map and the examples. The URI prefix will be http://covid19.genenetwork.org/resource/ followed by a unique identifier. To form the identifier I suggest a simple partial hash value of 24 letters or something computed over the metadata. wdyt?

These URIs can be published, also in journals, referring to other information. I think it will be quite valuable.

**Comment by pjotrp** [comment]
I suggest we compute the hash over the input files right before they get uploaded by https://github.com/arvados/bh20-seq-resource/blob/master/bh20sequploader/main.py and pass it in as an RDF triple. I'll check how I can paste that into pyshex. Would be nice if the URI can be parsed by humans, e.g.

http://covid19.genenetwork.org/resource/MT326090.1-faa1b4ca27

or something. Have to take care of URI encodings though.

**Comment by pjotrp** [comment]
@tetron I don't think we need to use info from Arvados. Beter make it a hash over inputs which can be reproduced by anyone. Just need to take care of newlines(!).

**Comment by pjotrp** [comment]
This should work: http://covid19.genenetwork.org/resource/MT326090.1

**Comment by pjotrp** [comment]
With http://covid19.genenetwork.org/resource/MT326090.1 we have collection http://collections.lugli.arvadosapi.com/c=10eaef75e0b875f81aa1f411c75370cf+126/. I think what I want to do is create an identifier that reuses that hash so http://covid19.genenetwork.org/resource/MT326090.1-10eaef75e0b8 will also work. Semantic versioning is handled by MT326090.1 and the Arvados hash ascertains we are talking about this dataset. It will end up as a triple:

```sparql
subject  pubseq:id  <http://covid19.genenetwork.org/resource/MT326090.1-10eaef75e0b8>
```
We'll need to create this triple after creating the collection. @tetron does this make sense?

I'll make sure the URI ends up as resolvable perma link.

**Comment by tetron** [comment]
There's a bunch of different sample identifiers available that mean somewhat different things.

1. The Arvados portable data hash (PDH).  This is a hash of the originally uploaded sequence and metadata file together.  This is immutable, we can't change the sequence or metadata without the PDH changing.  Currently, the metadata subjects are URIs that use this PDH.
2. The Arvados UUID.  This identifies the collection record that is the sequence and metadafile.  The collection record can be updated, and I've enabled Arvados collection versioning.  This makes it possible to update sample metadata while using the same ID.
3. The upstream sample ID.  This has an arbitrary format and unless qualified with a namespace, has potential for collisions between different data sets.  On the other hand, if properly qualified with a URI namespace which is also used by others, this is helpful for data consumers who wish to link the pubseq data with other data.

Is the goal here to choose a definitive "subject" id for the metadata export?  Or choose an identifier to construct the `http://covid19.genenetwork.org/resource/...` permalink?  Should the permalink be the RDF subject?  (But if the RDF subject is something we define, people who want to correlate our identifiers with the upstream identifiers have to do some extra work).

A thing we could do very easily is use the Arvados uuid:

http://covid19.genenetwork.org/resource/lugli-4zz18-p70fom6g3jdbcg1

So let's clarify exactly what we need to accomplish here.

**Comment by tetron** [comment]
(Copied from gitter)

There's at least 3 use cases

1. locating / fetching data from Arvados
2. metadata subjects in the triple store and sequence identifiers in other output like GFA files
3. a "permalink" to a page that describes an individual sequence.

I think 1 and 3 work best using the Arvados UUID like I suggested above.  Case 2 is neutral but maybe slightly more useful if they use a namespaced sample ID from upstream.

We have have both/all of the above (we already do) but there's always going to be a certain amount of translating between identifiers, so we should decide what we actually want.

**Comment by tetron** [comment]
Just to be clear, the thing I'm most trying to avoid is using the unqualified sample_id string as the id, because we have samples from different sources now, and although we've been lucky enough so far that they have sufficiently different id prefixes to tell them apart.  But at some point we may get a legitimate sample id collision.

I think the best thing to do is to continue use the Arvados portable data hash, but change the RDF subject to use the permalink.  @pjotrp suggested this in an email a few days ago:

http://covid19.genenetwork.org/resource/10eaef75e0b875f81aa1f411c75370cf+126

I have enabled collection versioning on the Arvados instance.  This means we will be able to update collections (to make metadata fixes) and the previous version will still be available.

I can add a feature to the analyzer service to update metadata when someone uploads a new metadata file, and looking up the sample_id.

**Comment by pjotrp** [comment]
Thinks @tetron. Very useful.
