### ISSUE TITLE
Allow for metadata updates

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#14]
It is possible the same sequence gets multiple metadata entries (e.g. for clinical outcome). So we need to be able to add metadata several times. Furthermore it is important to be able to update existing metadata - I think simply by adding versions.

**Comment by inutano** [comment]
I'd like to have a gist like approach. When you submit the data and metadata for the first time, you'll get the accession id. And then, when you want to submit the revised/fixed version of data or metadata, you need to submit them with the given accession id. The data will be stored as the version 2, which automatically assigned by the system. I don't think it'd be a good idea to let submitters manage the versions of their records.

**Comment by tetron** [comment]
This should be pretty straightforward, I think we want to do something like:

1. Enable Arvados collection versioning on the cluster
2. On the initial upload, print the Arvados UUID of the newly created collection
3. To do an update, upload a new collection with the new metadata and a collection property `for_update: X` which has the Arvados UUID returned earlier.
4. The orchestration script notices the `for_update` property and re-validates the sequence and metadata 
5. If it passes validation, copy the contents over to the collection to be updated (the old version will be automatically preserved) and re-run pipelines

**Comment by inutano** [comment]
Perfect! Arvados++

**Comment by pjotrp** [comment]
When we fix #103 it should be easy because every collection gets its own permanent identifier.
