### ISSUE TITLE
Share identifiers Redcap

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#21]
Redcap has a clinical HIPAA compliant database. We should share a field that refers to clinical patient information https://redcap-covid19.elixir-luxembourg.org/redcap/. One strain may have multiple records in Redcap.

**Comment by LLTommy** [comment]
How is this suppose to work with in terms of GDPR?

**Comment by pjotrp** [comment]
We can expose an identifier. No need to expose redcap data - though we could probably get some non-deterministic info.

**Comment by pjotrp** [comment]
It is easy to plug in such data. Waiting for a use case.
