### ISSUE TITLE
Docker image needs 'latest' tag

### ISSUE THREAD

**Issue by leechuck** [arvados/bh20-seq-resource#48]
Currently, `pangenome-generate.cwl` fails when trying to pull `jerven/spodgi`; looking at Dockerhub, it does not have the `latest` tag. Explicitly pulling `jerven/spodgi:0.0.5` fixes the problem.

Better solution would be to add the `latest` tag to the image on dockerhub.

**Comment by tetron** [comment]
Fixed workflow by adding the version tag
