### ISSUE TITLE
Compute HASH on inputs

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#55]
When submitting a sequence and metadata we can compute a hash value over the submission to make sure it is not already in the database.  People will accidentily resubmit stuff and there is no reason to trigger the pipeline. Or, @tetron, is this automatic in Arvados?

**Comment by tetron** [comment]
Yes, it already checks and ignores exact same submissions (same
fasta/metadata) as well as deduplicating sequences later on.
