### ISSUE TITLE
Move 10,000 JSON files into subdirectory

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#57]
Can we create a subdirectory for the JSON files? If we lead people to the latest results the current list is confusing.

**Comment by tetron** [comment]
It is in a subdirectory but the page doesn't support collapsing folders.

The thing to do here is to create a results page for the site instead of
just sending people to the generic Arvados collection display.

**Comment by pjotrp** [comment]
Problem is that *I* am lost too ;). So, the only way is to login with the Arvados client then. I'll need to set that up.

**Comment by tetron** [comment]
arv-ls is part of the arvados-python-client package which I think you
already ported to Guix.

**Comment by pjotrp** [comment]
Yup, thanks to @Millak! I just need to hone my Arvados skills again ;)

**Comment by pjotrp** [comment]
@tetron created a new page https://collections.lugli.arvadosapi.com/c=lugli-4zz18-z513nlpqm03hpca/
