### ISSUE TITLE
Make Keep links referrable for sequence files and metadata files

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#58]
The URIs in the database should be resolvable, e.g.

http://arvados.org/keep:00a6af865453564f6a59b3d2c81cc7c1+123/sequence.fasta

**Comment by pjotrp** [comment]
Ideally fetch the data itself.

**Comment by pjotrp** [comment]
Useful for https://github.com/arvados/bh20-seq-resource/issues/56

**Comment by tetron** [comment]
Yes I fixed that already the latest run should use different links that
work.

**Comment by pjotrp** [comment]
Does it include links for metadata files too?

**Comment by pjotrp** [comment]
Beautiful - already runs on http://covid19.genenetwork.org/. See http://collections.lugli.arvadosapi.com/c=00a6af865453564f6a59b3d2c81cc7c1+123/sequence.fasta

**Comment by tetron** [comment]
There are no links to metadata files because the metadata is loaded into
triples.

**Comment by pjotrp** [comment]
I am thinking backups and verification by the uploader. Can we store the metadata in the form of a file as it comes in and annotate that in a triple (I can do the latter)? We also need some annotation for the pipelines run, though that is a separate task.

**Comment by tetron** [comment]
Technically since they are stored in the same collection as the fasta you
already have a verifiable way to get the metadata yaml, by taking the fasta
URIs and replacing "sequence.fasta" with "metadata.yaml" at the end.

**Comment by pjotrp** [comment]
Beautiful. http://collections.lugli.arvadosapi.com/c=030bcb8fda7f19743157359f5855f7a6+126/sequence.fasta has http://collections.lugli.arvadosapi.com/c=030bcb8fda7f19743157359f5855f7a6+126/metadata.yaml

**Comment by tetron** [comment]
Verifiable in this case does require having the keep manifest so a backup
plan would need to stash those somewhere.

We don't have an official way of mirroring data from keep that doesn't
involve running the Arvados infrastructure however it is not terribly
difficult either it would just involve storing/reading data with a well
defined directory layout instead of fetching from a service.
