### ISSUE TITLE
Filter out list of sequences before building GFA

### ISSUE THREAD

**Issue by mandosoft** [arvados/bh20-seq-resource#68]
We need a script added to [pangenome-generate-cwl](https://github.com/arvados/bh20-seq-resource/blob/master/workflows/pangenome-generate/pangenome-generate.cwl) to remove the following sequences from the public sequence resource prior to creating a GFA output:

`00ef4c4427c0881a0030f7f400ce1ed0+123/sequence.fasta
1a191370cb868f80c824d93f9169599a+126/sequence.fasta
9e6fe32c3f7d281332ba958b5f62d109+123/sequence.fasta
bafb25a84fa5167d5a049fa43d607a44+126/sequence.fasta
9fe51f2847f3e8e3060c9ddebf3a41e5+123/sequence.fasta
d637278d9b95bbd1a5ef0bcd17a95c21+123/sequence.fasta
53fa57b401f3695feb0facf498f60871+123/sequence.fasta
392451211d0b7500ebaaa4e3182838be+123/sequence.fasta
bc7dcac01570c2fb81f16f76b98add9d+126/sequence.fasta
898c212f7a9d4984c382d782bad53fd4+123/sequence.fasta
f8001cec2144c59cbd851706b898ddfe+123/sequence.fasta
71063763aabd91e0b33d6861294bdff6+123/sequence.fasta
57dca4995c2186b11b67ab1cff0b005b+126/sequence.fasta
f95a298c57718bf290d9facdda59eb66+123/sequence.fasta
71da768110cd21ff99f5664bc335a4ec+126/sequence.fasta
06f5726c45483d0e8fdea3004f2c4adf+123/sequence.fasta
f9cea932bff8e83a2cb490c3bd694742+123/sequence.fasta
5914683bbe1ff047a163b3e57110f11b+126/sequence.fasta
27bb9a654a5f46e08888f55021d37b17+126/sequence.fasta
a9be2d60f66fd03a75418b40306ededc+126/sequence.fasta
aa1d1c497dabed0589c8ea6423179441+123/sequence.fasta
c6f8550cf6940591fea7de5f2159d88b+123/sequence.fasta
ab9c2241bda0599d20877ece1e1bc04e+126/sequence.fasta
5caa10de623c2384a31160c72a8f4f9c+126/sequence.fasta
0f24420528d58bff3468084aca3d7328+123/sequence.fasta
4887cadadce95997fed59d129e47b47b+126/sequence.fasta
e8e00929537a550b0989be12147d6241+126/sequence.fasta
7ebbc05a6949a6ce0637fa692af183ad+126/sequence.fasta
6566c86da5313159640092f16ac8a0cb+123/sequence.fasta
d04a38579335168796dd8d25f362ff8f+123/sequence.fasta
810d1e1012cbc4f63226159bd8b1fa08+123/sequence.fasta
4d40985616d6975a41a117c41fd38145+123/sequence.fasta
d2062c46515c5fffed7d27b95a9e32c9+126/sequence.fasta`

**Comment by josiahseaman** [comment]
This is a more short-term solution until we have #67 for our specific use case.

**Comment by tetron** [comment]
I'm adding an "exclude list" feature

**Comment by tetron** [comment]
This is resolved.

Exclude list is here https://workbench.lugli.arvadosapi.com/collections/lugli-4zz18-tzzhcm6hrf8ci8d

It will exclude sequences based on their fasta label, either the original label it was uploaded with, or the URI assigned by Arvados.
