### ISSUE TITLE
Add remark field to metadata

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#73]
A random remark field is probably a good idea. It can lead to additions to the schema. Also I think we can allow for additional RDF if people want that. At least give a proposal field.

**Comment by LLTommy** [comment]
Have a look at the example yaml [here](https://github.com/arvados/bh20-seq-resource/blob/master/example/maximum_metadata_example.yaml). Almost all sections do have a "additional_**_information_field" which is meant as a free text field to comment (as defined in SIO http://semanticscience.org/resource/SIO_001167). Does this answer your question?

**Comment by pjotrp** [comment]
> Does this answer your question?

Partly. One free text field for the whole form would be great. I am also thinking of allowing the injection of RDF, however. Maybe this is evil, but it would allow for a lot of freedom in adding metadata. Question is how you keep track of it ;)

**Comment by LLTommy** [comment]
Maybe I accept an additional comment file for the whole thing. However, I really don't know what additional metadata you want, especially if we include https://github.com/arvados/bh20-seq-resource/issues/77? You'd be lucky if you have all this metadata to go along with a submission, don't you think so? I'd say, let's try to keep up with what we have planned so far ... for now we have enough to address.

**Comment by pjotrp** [comment]
If someone wants to add a field for eye color they could do that immediately. We can follow with pyshex after if we think it is worth the trouble. It is that type of flexibility for end users. But then it may be better we just handle it ourselves (to avoid SPAM, for one).

**Comment by pjotrp** [comment]
Can be done when someone has a use case.
