### ISSUE TITLE
Create GFA subgraph for pangenome browser

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#81]
Ideally based on SPARQL queries.

**Comment by LLTommy** [comment]
But what are we looking for? Examples please, I hope we have a good chance that we can query for it already?

**Comment by pjotrp** [comment]
Yes, just needs to create a new GFA for the pangenome browser. Goes together with embedding the latter or feeding an external one.

**Comment by pjotrp** [comment]
Maybe never.
