### ISSUE TITLE
wrong predicate for lab_address

### ISSUE THREAD

**Issue by tetron** [arvados/bh20-seq-resource#88]
The predicate in the schema for `lab_address` is http://purl.obolibrary.org/obo/OBI_0600047 which is a typo because that's actually the predicate for `sample_sequencing_technology`.  Need to determine the correct predicate and fix the schema.

**Comment by LLTommy** [comment]
You are right, something went wrong there I assume. I looked at the spreadsheet and I found http://semanticscience.org/resource/SIO_000172 - "address"/ "http://semanticscience.org/resource/SIO_000172" - that would make a lot more sense. It would be the same predicate as for "submitter address".

**Comment by pjotrp** [comment]
Done, I presume.
