### ISSUE TITLE
Web page does not display correctly in Chromium

### ISSUE THREAD

**Issue by pjotrp** [arvados/bh20-seq-resource#9]
@BonfaceKilz having a small issue with the grid not aligning under the intro box. I can't figure it out. Can you see if you can fix it? Running at http://covid-19.genenetwork.org/

**Comment by pjotrp** [comment]
https://files.slack.com/files-pri/T010K0KRLTF-F011QNK3DMZ/image.png

**Comment by BonfaceKilz** [comment]
Let me have a look at it

**Comment by pjotrp** [comment]
Maybe the grid gets positioned at 0,0 and we need to put everything in the grid?

**Comment by BonfaceKilz** [comment]
@pjotrp Nope. That's not a grid issue. I use a CSS property called `column-count` which creates the nice looking masonry looking grid. FF sanely tells the columns not break when being rendered, but in Chromium, you have to explicitly do that. More of that [here](https://css-tricks.com/almanac/properties/b/break-inside/). Submitting a patch in a few :)
